#!/bin/bash

set -e

BASE=$(cd ${0%/*} && pwd)

echo ""
echo "REPOSITORIES"
echo "============"
echo ""

sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
                 https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

echo ""
echo "PACKAGES"
echo "========"
echo ""

sudo dnf install $(cat $BASE/packages)
curl -L https://nixos.org/nix/install | sh

echo ""
echo "SOURCE PACKAGES"
echo "==============="
echo ""

pushd $HOME
mkdir -p .local
pushd .local

if [ ! -e "distel" ]; then
    git clone https://github.com/massemanet/distel.git
fi
pushd distel
git pull
make
popd # distel

if [ ! -e "distel-completion" ]; then
    git clone https://github.com/sebastiw/distel-completion.git
else
pushd distel-completion
git pull
popd # distel-completion
fi

if [ ! -e "emacs-nav" ]; then
    git clone https://github.com/ancane/emacs-nav.git
else
pushd emacs-nav
git pull
popd # emacs-nav
fi

popd # .local
popd # $HOME

echo ""
echo "CONFIGURATION"
echo "============="
echo ""

pushd $BASE
rm -f $HOME/.bashrc $HOME/.bash_profile
stow -S -v -t $HOME bash
stow -S -v -t $HOME emacs
stow -S -v -t $HOME git
stow -S -v -t $HOME screen
stow -S -v -t $HOME ut4
popd # $BASE

echo ""
echo "DONE!"
echo ""
