#!/bin/bash

function extendPATH {
  if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
      export PATH=$1:$PATH
  fi
}

# source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# add local bin directory to path
# make doesn't always like the '~/blabla' notation
[[ -d $HOME/bin ]] && extendPATH $HOME/bin
[[ -d $HOME/.local/bin ]] && extendPATH $HOME/.local/bin

# include specific definitions
source ./aliases
source ./b9
source ./erlang
source ./git
source ./pkgconfig
