#!/bin/bash

# source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# add local bin directory to path
[[ -d ~/bin ]] && export PATH="~/bin:$PATH"
[[ -d ~/.local/bin ]] && export PATH="~/.local/bin:$PATH"

# include specific definitions
source ./aliases
source ./b9
source ./erlang
source ./git
source ./pkgconfig
